### ISSUE TITLE
Modal content and email subjects

### ISSUE THREAD

**Issue by Reillyhewitson** [XFour-IT/XFour-Site#4]
@benjisoft I need these to complete the new modals. Close this issue when cisco partnership is confirmed, so we can add the content.

**Comment by benjisoft** [comment]
Please clarify this

**Comment by Reillyhewitson** [comment]
I need content, so descriptions whaterver for each partner/project. This will include Cisco.

**Comment by Reillyhewitson** [comment]
Hey @benjisoft any progress?

**Comment by benjisoft** [comment]
This has been completed now
