### ISSUE TITLE
Horrendous SEO

### ISSUE THREAD

**Issue by benjisoft** [XFour-IT/XFour-Site#8]
Our SEO is awful and only speaks about Shopify. This needs to be improved urgently.

**Comment by benjisoft** [comment]
I'll get on top of writing us something unless anyone else wants to take this.

**Comment by benjisoft** [comment]
@Reillyhewitson Could you implement this for me once they are written, please.

**Comment by Reillyhewitson** [comment]
@benjisoft Why?

**Comment by benjisoft** [comment]
Fixed in commit cb67691b9a6f4ad2890e9b29bd3ef48f2d41b1ee
